### PR TITLE
Features dg

### PR DESCRIPTION
**Pull request by ratones**
fixes for css and sort issues.
I implemented a custom sort function in DataSource, to deal with moment dates.

### CODE REVIEW

**Comment by ratones** [comment]
@adarshpastakia 
I took the liberty of rewriting a major part of `ui-dg-datagrid` to suit my projects requirements. 
I added group rows and a few other features.
The changes are backward compatible, so the initial configuration of the grid still works.
You can check it out at https://ratones.github.io, which is a copy of your site, with the datagrid page modified. The first grid contains some new features, the second grid is the original one.
The sources are available in the `ui-dg-grouprow` branch of the fork.
I will continue to work on this, to add some other things that I need.
The features are not production ready, I just wanted to illustrate some principles.
If you want to merge this changes in version 4.0.0,  or have suggestions/comments on my approach, please let me know.

**Comment by adarshpastakia** [comment]
@ratones 
was a bit busy with work stuff, however i did check your code I'm still trying to work out the data source functionality, its a bit difficult to test haven't got a server api to test against.

for now i did add ui-dg-cell to create cell display using aurelia view-compiler, as for creating an editable row i was thinking of making it similar to how extjs displays the edit record http://examples.sencha.com/extjs/6.2.0/examples/kitchensink/#row-editing

**Comment by adarshpastakia** [comment]
@ratones 
on branch v4.0.0 i did manage to add the layout for editable rows, since i changed the entire datagrid layout to use flexbox divs instead of tables. unfortunately i cannot publish the demo build since the GitHub pages only works on master branch, and i couldn't open a pull request on your repo coz there is no branch v4.0.0

still have a few more things to do
- Issue when discarding changes
- Indicator for dirty cell
- Combobox/Dropdown editor
- Checkbox/Switch editor

**Comment by ratones** [comment]
@adarshpastakia That is great news!
I will create a branch for pull request.

**Pull request closed without merging**
