### PR TITLE
editable work in progress

### PR DESCRIPTION
**Pull request by ratones**

### CODE REVIEW

**Comment by adarshpastakia** [comment]
@ratones i have created a branch v4.0.0 for the major updates for datagrid and data-sources, need to restructure the datagrid layout for locked columns without using css3 sticky and also need to work out the best possible way of using templates for rendering each column's display

So far the updates will include
* Updated layout
* Cell rendering from template
* DataSource
* Editable rows
* Column groups

**Comment by ratones** [comment]
@adarshpastakia 
I'm woking on editable rows these days.
What is done:
I created another custom element named `ui-dg-cell` which handles the column template rendering. It becomes a children of `ui-dg-row`. This element observes the value edited and attaches a class(`ui-value-changed`) to the table cell if the data changes. This is useful as a visual indicator of cells that has changed.
The row can enter editMode either by dblclick or by calling a method on the grid VM which sets the `selected` record in edit mode.
I added an editor for most of the data-types, including email, phone, etc.
I added some methods in `ui-dg-datagrid` for keeping track of all changes, adding possibility to revert changes, redo changes and get the changed records. This works fine for first level records, however I'm struggling write now to figure out a method to keep track of subdata records. This seems to be harder then I thought... 
For this, I added a bindable property to grid, `recid`, which stores the primary key name of the record, defaults to "id" if none provided. This helps keeping track of changed record. However, since subdata can have the same values as primary key this doesn't help...
I added a private property called `changes` which stores the changed records as array based on their primary key. The changed objects have two properties: `oldValue` and `newValue` for each property that changed. 
 I'm not sure though if the way you implemented subdata records permits duplicate keys for these records. In the example page, the subrecords have the same ids as first level records. If you have any thoughts, please let me know.
Another problem I'm facing is in the paged grid. When page is changed, the rows of the previous page are detached. This forces me to add a method to the grid, to check for changes when the row is binded again. This is also solvable if I figure out how to keep track of changed records...
Write now I'm working on adding a `parentId` property to each subdata record. Then, in `changes` object I can add a property to each record `childrens` which will store the changes made to subrecords, regardless of the level of subdata. However this implies some pretty heavy calculation and logic...
I'll keep you posted with progress. In the mean time, if you have any questions, please contact me. I saw that you merged the 4.0.0 branch with the master, removing the data source.

**Comment by adarshpastakia** [comment]
@ratones i did merge the master which removed the data source update, but i reverted those changes back into v4.0.0

I'm planning on updating the layout soon, i had done that before but having six tables in the dom somehow didn't feel right but i haven't been able to find a better way to have locked columns that would work on all browsers. 

i will try to write a simple doc about the record editing if you like, i have used it before with ExtJS and the way in which its done there is each record maintains a `isDirty` flag and `__original__` object which only gets updated by saving the dirty record. that way when you do a post you could pull only the dirty records from the data-source.

**Comment by ratones** [comment]
@adarshpastakia Yes, I thought about that too. The `isDirty` solution would solve some problems, but there is a performance issue when trying to get all the changes, especially when the records are children of another record and you go 2 or three levels down.
Storing the changed records would be an alternative, but I think i should preserve the structure of data.
I.e: Assume following data structure:
    [
       {id:1,name:'Test1',subdata:[
         {id:1, name:'Subdata1'},
         {id:2, name:'Subdata2', subdata:[{id:1,name:'level2'}]}
       ]}
    ]
If `level2` item changes, the dirty items should keep the same structure, smth like
    [{id:1,isDirty:true,subdata:[
      {id:2, isDirty:true,subdata:[{
        id:1,isDirty:true, name:'leve2Changed',_original_:{name:'level2}}}
      }]
    ]}]

This way you would know which record changed and how to post it to server.
I would like to see a doc about record editing, maybe there is a better solution.
In my projects, the server knows how to handle records with child records recursive, based on `isDirty` property, but the received data should keep the original structure. It's true, though that the child records came from other database related tables. May be the use case here is different, i.e the records came from the same table and are unique identified by a primary key, in which case, the structure is no longer important. Also, if the data is local, the structure is not important, since the update is done automagicaly by the framework.
Perhaps we should identify the use case for expandable rows. For instance, if the child records came from another table and have different structure, the expanded row should provide a wrapper for another grid, with its own functionality.  Else, all the records should have a unique key, regardless if they are parent or child. That will solve all the issues.

**Pull request closed without merging**
